### ISSUE TITLE
微调或是从头训练

### ISSUE THREAD

**Issue by panxin801** [Executedone/Chinese-FastSpeech2#12]
您好，感谢您公开这么好的工作。我现在有2800条的语音，想训练一个prosody 模型。您觉得是 fintune prosody 模型还是从头训练效果会更好一些呢？ 谢谢您的回复

**Comment by Executedone** [comment]
看需要吧，如果是中文的话一般不需要，除非你的数据发音方式和正常的停顿节奏不一样；如果涉及到英文或别的语言要重新训练

**Comment by panxin801** [comment]
明白了，谢谢您
