### ISSUE TITLE
韵律模型

### ISSUE THREAD

**Issue by wizardk** [Executedone/Chinese-FastSpeech2#3]
你好，请问韵律模型是使用什么数据训练的？

**Comment by Executedone** [comment]
也是用标贝数据训练的，根据#分隔符确定韵律边界

**Comment by wizardk** [comment]
请问如果不微调的话，效果差异大吗？

**Comment by Executedone** [comment]
差异还是挺大的，主要体现在节奏停顿不太好。实际上也可以不用bert去做，lstm应该也足够了，韵律模型相对来说还是一个比较简单的任务

**Comment by MaxMax2016** [comment]
您好，这个韵律模型的训练代码方便开源吗？

**Comment by Executedone** [comment]
我抽个空整理一下代码

**Comment by wizardk** [comment]
@Executedone 再请教下，微调时，是仅增加的全连接层的参数参与训练，还是整个bert的预训练主干网络也参与训练？

**Comment by Executedone** [comment]
我是整个网络一起训练的

**Comment by wizardk** [comment]
谢谢
