### ISSUE TITLE
韵律模型训练过程

### ISSUE THREAD

**Issue by HandsLing** [Executedone/Chinese-FastSpeech2#4]
请问能提供韵律模型训练的训练流程和代码吗？

**Comment by Executedone** [comment]
韵律模型的训练比较复杂，尤其是数据处理那块，要把音素与韵律对齐，这块代码没整理

**Comment by langlanglofa** [comment]
韵律模型部分，处理后的训练数据，可以给一两个例子即可，训练代码可以先放出来大家共同学习下？
