### ISSUE TITLE
如何支持流式tts输出

### ISSUE THREAD

**Issue by zhaolibo1989** [Executedone/Chinese-FastSpeech2#6]
您好，你的项目代码对我的帮助非常大。特别是优化后的语音效果比较让我满意。非常感谢！
我想在目前的基础上做进一步的开发，比如让合成后的语音数据能流式地输出到其他地方。应用场景是，比如输入一段新闻稿，合成后，流式地输出到其他设备。主要借鉴了飞浆的流式TTS功能。但设计过程中遇到了一此问题，希望能得到您的指点或建议。
主要问题：是否支持分批次推理完整文本的其中一部分，如果可以应该如何做到？
我主要参考了飞浆(paddle)其中一个demo的代码，主要从[这里](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/speech_web/speech_server/src/SpeechBase/tts.py#L83)开始。
结合本项目的代码，我觉得应该从[这里](https://github.com/Executedone/Chinese-FastSpeech2/blob/main/synthesize_all.py#L307)切入。
不知道这个方向有没有什么不托，但实现起来有些让我”挠头“ :-)

**Comment by Executedone** [comment]
抱歉，流式tts我还没接触过，不过有几个建议看看是否能帮助到您：
1、可以根据demo的原理看看流式生成需要哪些部件，每个部件是什么样的；
2、是根据demo对项目代码进行改造还是把项目代码的模型整合到demo去，要看流式的工作原理；
3、确定流式的输入输出，看看能否把两边的输入输出联系起来

**Comment by zhaolibo1989** [comment]
> 抱歉，流式tts我还没接触过，不过有几个建议看看是否能帮助到您： 1、可以根据demo的原理看看流式生成需要哪些部件，每个部件是什么样的； 2、是根据demo对项目代码进行改造还是把项目代码的模型整合到demo去，要看流式的工作原理； 3、确定流式的输入输出，看看能否把两边的输入输出联系起来

没关系。依然感谢您的建议，我正在分析原理的路上。
