### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './preprocessor/expanded_embeds.pkl'

### ISSUE THREAD

**Issue by xiaoru168** [Executedone/Chinese-FastSpeech2#7]
提示这个文件找不到，能提供一下么？expanded_embeds.pkl
Prepare training ...
Traceback (most recent call last):
  File "E:\python\Chinese-FastSpeech2\train.py", line 202, in <module>
    main(args, configs)
  File "E:\python\Chinese-FastSpeech2\train.py", line 28, in main
    dataset = Dataset(
  File "E:\python\Chinese-FastSpeech2\dataset.py", line 31, in __init__
    with open(self.expanded_char_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './preprocessor/expanded_embeds.pkl'

**Comment by Aibeeeee** [comment]
> 提示这个文件找不到，能提供一下么？expanded_embeds.pkl Prepare training ... Traceback (most recent call last): File "E:\python\Chinese-FastSpeech2\train.py", line 202, in main(args, configs) File "E:\python\Chinese-FastSpeech2\train.py", line 28, in main dataset = Dataset( File "E:\python\Chinese-FastSpeech2\dataset.py", line 31, in **init** with open(self.expanded_char_path, 'rb') as f: FileNotFoundError: [Errno 2] No such file or directory: './preprocessor/expanded_embeds.pkl'

可以通过biaobei.py得到，程序是能跑通的~不过还需要自己另外用mfa训练并生成TextGrid对齐文件，这一步就挺费时。。。

**Comment by yihaoyao402** [comment]
> > 提示这个文件找不到，能提供一下么？expanded_embeds.pkl Prepare training ... Traceback (most recent call last): File "E:\python\Chinese-FastSpeech2\train.py", line 202, in main(args, configs) File "E:\python\Chinese-FastSpeech2\train.py", line 28, in main dataset = Dataset( File "E:\python\Chinese-FastSpeech2\dataset.py", line 31, in **init** with open(self.expanded_char_path, 'rb') as f: FileNotFoundError: [Errno 2] No such file or directory: './preprocessor/expanded_embeds.pkl'
> 
> 可以通过biaobei.py得到，程序是能跑通的~不过还需要自己另外用mfa训练并生成TextGrid对齐文件，这一步就挺费时。。。

想请问您一下跑通代码的具体流程可以吗？有AISHELL的TextGrid后先运行了preprocessor.py，再train发现缺失pkl文件，python biaobei.py时报错
FileNotFoundError: [Errno 2] No such file or directory: '/expanded_chars_length.json' 
所以不太清楚关于AISHELL和biaobei数据集所需设置的config和具体的预处理流程，不知道您能否分享一下
